### ISSUE TITLE
Linux: thunderbird.desktop additional actions doesn't work

### ISSUE THREAD

**Issue by lamyergeier** [mozilla/sumo-kb#4]
I edited the `thunderbird.desktop`  file and appended 2 more actions at the end as follows:

```ini
[Desktop Entry]
Encoding=UTF-8
Name=Thunderbird Mail
Comment=Send and receive mail with Thunderbird
GenericName=Mail Client
Keywords=Email;E-mail;Newsgroup;Feed;RSS;Calendar;Contact
Exec=/mnt/Data/opt/bin/thunderbird %u
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=/mnt/Data/opt/Setup/Thunderbird/thunderbird-115/thunderbird/chrome/icons/default/default128.png
Categories=Application;Network;Email;
MimeType=x-scheme-handler/mailto;application/x-xpinstall;
StartupNotify=true
Actions=Compose;Contacts;Calendar;ProfileManager

[Desktop Action Compose]
Name=Compose New Message
Exec=thunderbird -compose

[Desktop Action Contacts]
Name=Contacts
Exec=thunderbird -addressbook

[Desktop Action Calendar]
Name=Calendar
Exec=thunderbird -calendar

[Desktop Action ProfileManager]
Name=Profile Manager
Exec=thunderbird --ProfileManager
```

### Issue

The actions are displayed in Gnome Dash as shown below. But when I click the additional actions that I added `Calendar` and `Profile Manager`, nothing happens. Any suggestions why?

![image](https://github.com/mozilla/sumo-kb/assets/42092626/6d1fc8ce-b0a7-42c2-94b2-b2ae91839659)

**Comment by philg-dev** [comment]
I think your problem is that the `exec` command of all your right-click actions is just `thunderbird`, but `thunderbird` seems to not be in your `$PATH`, at least judging from the fact the the normal `exec` command to launch the application contains an explicit path `exec=/mnt/Data/opt/bin/thunderbird`.

I tested your file and on my end and the actions you've defined were working once I replaced the paths to your thunderbird executable with just `thunderbird` (since my thunderbird executable is available in `$PATH`) and the icon path with the one that works on my system.
