### ISSUE TITLE
Add a custom action to the Desktop File

### ISSUE THREAD

**Issue by lamyergeier** [mozilla/sumo-kb#7]
For example I would like to add the following to the context menu of the icon

```
Actions=Compose;Contacts;Calendar;ProfileManager;SafeMode

[Desktop Action SafeMode]
Name=Safe Mode
Exec=thunderbird --safe-mode
```

But this does not creates option in the context menu. Any ideas?

**Comment by philg-dev** [comment]
I just fiddled around with it a little bit and for some reason it didn't show up for me immediately either.

I think you could either remove the `thunderbird.desktop` file and add it again, rather than an in-place replacement... Or another clean solution that worked for me was to restart the GNOME shell (Hit `ALT + F2` to get the gnome shell command prompt and enter `r` or `restart` to restart the gnome shell. All your applications should stay open when doing this.)

Afterwards your option(s) should appear in the context-menu of your Thunderbird icon.
